flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.10.1
- aeson-1.2.3.0
- aeson-qq-0.8.2
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- appar-0.1.4
- async-2.1.1.1
- attoparsec-0.13.2.0
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base64-bytestring-1.0.0.1
- basement-0.0.4
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.3
- call-stack-0.1.0
- case-insensitive-1.2.0.10
- colour-2.3.3
- cookie-0.4.3
- cpphs-1.20.8
- cryptonite-0.24
- data-default-class-0.1.2.0
- dlist-0.8.0.3
- easy-file-0.2.1
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.10
- file-embed-0.0.10.1
- foundation-0.0.17
- hashable-1.2.6.1
- haskell-src-exts-1.19.1
- haskell-src-meta-0.8.0.1
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- hspec-wai-0.9.0
- hspec-wai-json-0.9.0
- http-api-data-0.3.7.1
- http-date-0.0.6.1
- http-media-0.7.1.1
- http-types-0.10
- http2-1.6.3
- integer-logarithms-1.0.2
- iproute-1.7.1
- lifted-base-0.2.3.11
- memory-0.14.8
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.2.2
- mtl-2.2.1
- natural-transformation-0.4
- network-2.6.3.2
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.0.0
- parsec-3.1.11
- polyparse-1.12
- primitive-0.6.2.0
- psqueues-0.2.4.0
- quickcheck-io-0.2.0
- random-1.1
- resourcet-1.1.9
- safe-0.3.15
- scientific-0.3.5.2
- semigroups-0.18.3
- servant-0.12
- servant-server-0.12
- setenv-0.1.1.3
- simple-sendfile-0.2.25
- split-0.2.3.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- syb-0.7
- system-filepath-0.4.13.4
- tagged-0.8.5
- text-1.2.2.2
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.3.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- th-orphans-0.13.4
- th-reify-many-0.1.8
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.5
- unix-time-0.3.7
- unordered-containers-0.2.8.0
- uri-bytestring-0.3.0.1
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vault-0.3.0.7
- vector-0.12.0.1
- void-0.7.2
- wai-3.2.1.1
- wai-app-static-3.1.6.1
- wai-extra-3.0.20.1
- wai-logger-2.3.0
- warp-3.2.13
- word8-0.1.3
- zlib-0.6.1.2
- aeson-pretty-0.8.5
- hex-0.1.2
- cmdargs-0.10.18
resolver: ghc-7.10.2
